[package]
name = "usync"
version = "0.1.0"
edition = "2021"
license = "MIT"
authors = ["kprotty"]
readme = "README.md"
homepage = "https://github.com/kprotty"
documentation = "https://docs.rs/usync"
description = "fast, drop-in, replacement for std::sync"
categories = ["concurrency", "data-structures"]
keywords = [
    "atomic", "lock", 
    "mutex", "rwlock", "condvar", "once",
    "parallel", "parallelism", "thread", "concurrent", "performance",
]

[dependencies]
cfg-if = "1.0.0"

[features]
nightly = []

[target.'cfg(unix)'.dependencies]
libc = "0.2.95"

[target.'cfg(target_os = "redox").dependencies']
redox_syscall = "0.2.8"

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.34.0", features = [
    "Win32_System_Threading",
] }