[package]
name = "usync"
version = "0.0.0"
edition = "2021"
license = "Apache-2.0"
authors = ["kprotty"]
readme = "README.md"
homepage = "https://github.com/kprotty"
documentation = "https://docs.rs/usync"
description = "small, fast, synchronization primitives"
categories = ["concurrency", "data-structures"]
keywords = [
    "atomic", "lock", "lock-free", "non-blocking", 
    "mutex", "rwlock", "condvar", "once", "barrier",
    "parallel", "parallelism", "thread", "concurrent", "performance",
]
